require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable # rubocopの新機能をactiveにする
  Exclude:
    - "assets/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "log/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

# html_safe、raw、safe_concat などの出力安全コールの使用をチェック
Rails/OutputSafety:
  Enabled:
    - 'app/helpers/devise_helper.rb'

# デフォルト値のないカラムでの NOT NULL 制約を許可
Rails/NotNullColumn:
  Enabled:
    - 'db/migrate/20210801061841_add_column_to_users.rb'

# メソッドの ABC サイズが構成された最大値を 25 に変更
Metrics/AbcSize:
  Max: 25
# ブロック長さが最大値を超えているかどうかをチェックから spec ファイルを解除
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
# メソッドの最大行数を 20 に変更
Metrics/MethodLength:
  Max: 20

# ヒアドキュメントで END と EO* の使用を許可
Naming/HeredocDelimiterNaming:
  Exclude:
    - 'app/helpers/devise_helper.rb'

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可
Style/Documentation:
  Enabled: false

# frozen_string_literal の指定強制を解除
Style/FrozenStringLiteralComment:
  Enabled: false

# 1行の最大
Layout/LineLength:
  Max: 160

# %w, %i を使用強制を解除（使用しても使用しなくてもOKにする）
Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# 許可された接頭辞かどうかのチェックを解除
RSpec/ContextWording:
  Enabled: false

# トップレベルの describe の第一引数が定数であるかのチェックを解除
RSpec/DescribedClass:
  Enabled: false

# 最後のレットブロックの後に空の行があるかどうかのチェックを解除
  # it が一行しかない場合などは少し見づらくなるため
RSpec/EmptyLineAfterFinalLet:
  Enabled: false
  
# 長い例のチェックを解除  
RSpec/ExampleLength:
  Enabled: false

# 一貫した暗黙の期待スタイルが使われているかどうかのチェックを解除
RSpec/ImplicitExpect:
  Enabled: false
  
# スペック内のインスタンス変数使用時の使用状況・使用方法のチェックを解除
RSpec/InstanceVariable:
  Enabled: false
  
# 明示的に名前を付けているかどうかのチェックを解除
  # テストコードが読みにくくなる場合がある為
RSpec/NamedSubject:
  Enabled: false

# 期待値がスパイを使って設定されているかどうかのチェックを解除
RSpec/MessageSpies:
  Enabled: false

# expect 呼び出しが多すぎるかどうかのチェックを解除
  # 複数定義する場合があるため
RSpec/MultipleExpectations:
  Enabled: false

# 入れ子になったグループチェックを解除
  # デフォルトの ３ だと少ない場合があり読みづらくなる可能性がある為
RSpec/NestedGroups:
  Max: 5
